inherit_from: .rubocop_airbnb.yml

Rails:
   Enabled: true
AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "spec/spec_helper.rb"
LineLength:
  Max: 200
Style/MixinUsage:
  Enabled: false
